# Generated by Django 4.1.7 on 2023-06-06 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotus', '0002_remove_info_summary_alter_info_slug_alter_info_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Data',
            new_name='Lod',
        ),
        migrations.RenameField(
            model_name='info',
            old_name='data',
            new_name='lod',
        ),
    ]
