# Generated by Django 4.1.7 on 2023-06-06 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotus', '0003_rename_data_lod_rename_data_info_lod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
